version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db 
    ports:
      - "3000:3000"
    volumes:
      - .:/myproject:cached 
      #ソケット通信用ファイルをnginxコンテナと共有
      - tmp-data:/myproject/tmp/sockets
      #画像データとかをnginxと共有
      - public-data:/myproject/public

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --socket=/tmp/mysql.sock
    ports: 
      - '3306:3306'
    environment:
      MYSQL_DATABASE: proscons_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    #dbのデータを永続化しておく
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/socket_tmp:/tmp

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/myproject/tmp/sockets
      - public-data:/myproject/public
    depends_on:
      - web 

volumes:
  public-data:
  tmp-data:
  mysql-data: